
#  *****************************************************************
#             EXODIFF	(Version: 2.90) Modified: 2018-02-15
#             Authors:  Richard Drake, rrdrake@sandia.gov
#                       Greg Sjaardema, gdsjaar@sandia.gov
#             Run on    2019/01/31   13:04:33 MST
#  *****************************************************************

#  FILE 1: /Users/djlittl/PeridigmCurrent/peridigm/test/verification/SimpleImplicitDiffusion/SimpleImplicitDiffusion.e
#   Title: Peridigm
#          Dim = 3, Blocks = 1, Nodes = 210, Elements = 210, Nodesets = 3, Sidesets = 0
#          Vars: Global = 0, Nodal = 2, Element = 1, Nodeset = 0, Sideset = 0, Times = 21


# ==============================================================
#  NOTE: All node and element ids are reported as global ids.

# NOTES:  - The min/max values are reporting the min/max in absolute value.
#         - Time values (t) are 1-offset time step numbers.
#         - Element block numbers are the block ids.
#         - Node(n) and element(e) numbers are 1-offset.

COORDINATES absolute 1.e-6    # min separation not calculated

TIME STEPS relative 1.e-6 floor 0.0     # min:               0 @ t1 max:               1 @ t21


# No GLOBAL VARIABLES

NODAL VARIABLES relative 1.e-6 floor 0.0
	Flux_Divergence  absolute 1.176621700000e-04    # min:               0 @ t1,n1	max:       117.66217 @ t21,n5
	Temperature      absolute 3.730000000000e-04    # min:             273 @ t1,n1	max:             373 @ t21,n190

ELEMENT VARIABLES relative 1.e-6 floor 0.0
	Number_Of_Neighbors  absolute 3.000000000000e-05    # min:               9 @ t1,b1,e1	max:              30 @ t1,b1,e50

# No NODESET VARIABLES

# No SIDESET VARIABLES


