DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX        absolute 1.0E-9
	DisplacementY        absolute 1.0E-9
	DisplacementZ        absolute 1.0E-9
	ForceX               absolute 1.0E-3
	ForceY               absolute 1.0E-3
	ForceZ               absolute 1.0E-3
ELEMENT VARIABLES absolute 1.E-12
	Deformation_GradientXX absolute 1.0E-12
	Deformation_GradientXY absolute 1.0E-12
	Deformation_GradientXZ absolute 1.0E-12
	Deformation_GradientYX absolute 1.0E-12
	Deformation_GradientYY absolute 1.0E-12
	Deformation_GradientYZ absolute 1.0E-12
	Deformation_GradientZX absolute 1.0E-12
	Deformation_GradientZY absolute 1.0E-12
	Deformation_GradientZZ absolute 1.0E-12
	StrainXX absolute 1.0E-12
	StrainXY absolute 1.0E-12
	StrainXZ absolute 1.0E-12
	StrainYX absolute 1.0E-12
	StrainYY absolute 1.0E-12
	StrainYZ absolute 1.0E-12
	StrainZX absolute 1.0E-12
	StrainZY absolute 1.0E-12
	StrainZZ absolute 1.0E-12
	StressXX absolute 1.0E-2
	StressXY absolute 1.0E-2
	StressXZ absolute 1.0E-2
	StressYX absolute 1.0E-2
	StressYY absolute 1.0E-2
	StressYZ absolute 1.0E-2
	StressZX absolute 1.0E-2
	StressZY absolute 1.0E-2
	StressZZ absolute 1.0E-2
