DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX        absolute 1.0E-9
	DisplacementY        absolute 1.0E-9
	DisplacementZ        absolute 1.0E-9
	ForceX               absolute 1.0E-3
	ForceY               absolute 1.0E-3
	ForceZ               absolute 1.0E-3
ELEMENT VARIABLES absolute 1.E-12
	Deformation_GradientXX absolute 1.0E-12
	Deformation_GradientXY absolute 1.0E-12
	Deformation_GradientXZ absolute 1.0E-12
	Deformation_GradientYX absolute 1.0E-12
	Deformation_GradientYY absolute 1.0E-12
	Deformation_GradientYZ absolute 1.0E-12
	Deformation_GradientZX absolute 1.0E-12
	Deformation_GradientZY absolute 1.0E-12
	Deformation_GradientZZ absolute 1.0E-12
	Green_Lagrange_StrainXX absolute 1.0E-12
	Green_Lagrange_StrainXY absolute 1.0E-12
	Green_Lagrange_StrainXZ absolute 1.0E-12
	Green_Lagrange_StrainYX absolute 1.0E-12
	Green_Lagrange_StrainYY absolute 1.0E-12
	Green_Lagrange_StrainYZ absolute 1.0E-12
	Green_Lagrange_StrainZX absolute 1.0E-12
	Green_Lagrange_StrainZY absolute 1.0E-12
	Green_Lagrange_StrainZZ absolute 1.0E-12
	Cauchy_StressXX absolute 1.0E-2
	Cauchy_StressXY absolute 1.0E-2
	Cauchy_StressXZ absolute 1.0E-2
	Cauchy_StressYX absolute 1.0E-2
	Cauchy_StressYY absolute 1.0E-2
	Cauchy_StressYZ absolute 1.0E-2
	Cauchy_StressZX absolute 1.0E-2
	Cauchy_StressZY absolute 1.0E-2
	Cauchy_StressZZ absolute 1.0E-2
