DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX            absolute 1.0E-12
	DisplacementY            absolute 1.0E-12
	DisplacementZ            absolute 1.0E-12
	VelocityX                absolute 1.0E-12
	VelocityY                absolute 1.0E-12
	VelocityZ                absolute 1.0E-12
	AccelerationX            absolute 1.0E-12
	AccelerationY            absolute 1.0E-12
	AccelerationZ            absolute 1.0E-12
	ForceX                   absolute 1.0E-12
	ForceY                   absolute 1.0E-12
	ForceZ                   absolute 1.0E-12
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume          absolute 1.0E-12
	Dilatation               absolute 1.0E-12
	Radius                   absolute 1.0E-12
