DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX   absolute 1.0E-16
	DisplacementY   absolute 1.0E-16
	DisplacementZ   absolute 1.0E-16
	VelocityX       absolute 1.0E-16
	VelocityY       absolute 1.0E-16
	VelocityZ       absolute 1.0E-16
ELEMENT VARIABLES absolute 1.E-12
	Deformation_GradientXX absolute 1.0E-14
	Deformation_GradientYY absolute 1.0E-14
	Deformation_GradientZZ absolute 1.0E-14
	Deformation_GradientXY absolute 1.0E-14
	Deformation_GradientYZ absolute 1.0E-14
	Deformation_GradientZX absolute 1.0E-14
	Deformation_GradientYX absolute 1.0E-14
	Deformation_GradientZY absolute 1.0E-14
	Deformation_GradientXZ absolute 1.0E-14
