DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
ELEMENT VARIABLES absolute 1.E-12
	Deformation_GradientXX absolute 1.0E-9
	Deformation_GradientYY absolute 1.0E-9
	Deformation_GradientZZ absolute 1.0E-9
	Deformation_GradientXY absolute 1.0E-9
	Deformation_GradientYZ absolute 1.0E-9
	Deformation_GradientZX absolute 1.0E-9
	Deformation_GradientYX absolute 1.0E-9
	Deformation_GradientZY absolute 1.0E-9
	Deformation_GradientXZ absolute 1.0E-9
