DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX             absolute 1.0E-9
	DisplacementY             absolute 1.0E-9
	DisplacementZ             absolute 1.0E-9
	VelocityX                 absolute 1.0E-9
	VelocityY                 absolute 1.0E-9
	VelocityZ                 absolute 1.0E-9
	ForceX                    absolute 1.0E-3
	ForceY                    absolute 1.0E-3
	ForceZ                    absolute 1.0E-3
ELEMENT VARIABLES absolute 1.E-12
	Volume absolute 1.0E-12
	Radius absolute 1.0E-12
	Weighted_Volume absolute 1.0E-14
	Dilatation absolute 1.0E-10
