DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX             absolute 1.0E-9
	DisplacementY             absolute 1.0E-9
	DisplacementZ             absolute 1.0E-9
	VelocityX                 absolute 5.0E-8
	VelocityY                 absolute 5.0E-8
	VelocityZ                 absolute 5.0E-8
	External_Force_DensityX   absolute 5.0E-8
	External_Force_DensityY   absolute 5.0E-8
	External_Force_DensityZ   absolute 5.0E-8
	ForceX                    absolute 5.0E-8
	ForceY                    absolute 5.0E-8
	ForceZ                    absolute 5.0E-8
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume           absolute 1.0E-12
	Dilatation                absolute 1.0E-12
