<Tolerances>
  <Tolerance variable="X_Position" value="1.0e-9"/>
  <Tolerance variable="Y_Position" value="1.0e-9"/>
  <Tolerance variable="Z_Position" value="1.0e-9"/>
  <Tolerance variable="X_Velocity" value="1.0e-9"/>
  <Tolerance variable="Y_Velocity" value="1.0e-9"/>
  <Tolerance variable="Z_Velocity" value="1.0e-9"/>
  <Tolerance variable="Weighted_Volume" value="1.0e-12"/>
  <Tolerance variable="Dilatation" value="1.0e-12"/>
</Tolerances>
