DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX   absolute 1.0E-9
	DisplacementY   absolute 1.0E-9
	DisplacementZ   absolute 1.0E-9
	VelocityX       absolute 5.0E-8
	VelocityY       absolute 5.0E-8
	VelocityZ       absolute 5.0E-8
	Force_DensityX  absolute 1.0
	Force_DensityY  absolute 1.0
	Force_DensityZ  absolute 1.0
	Fluid_Pressure_U absolute 1.E-9
	Flux_Density    absolute 1.E-9
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume absolute 1.0E-12
	Dilatation      absolute 1.0E-12
