DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX   absolute 1.0E-9
	DisplacementY   absolute 1.0E-9
	DisplacementZ   absolute 1.0E-9
	VelocityX       absolute 1.0E-9
	VelocityY       absolute 1.0E-9
	VelocityZ       absolute 1.0E-9
	Force_DensityX  absolute 1.0E-8
	Force_DensityY  absolute 1.0E-8
	Force_DensityZ  absolute 1.0E-8
ELEMENT VARIABLES absolute 1.E-12
	Dilatation      absolute 1.0E-10
	Lambda          absolute 1.0E-3
