DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX            absolute 1.0E-130
	DisplacementY            absolute 1.0E-130
	DisplacementZ            absolute 1.0E-130
	VelocityX                absolute 1.0E-130
	VelocityY                absolute 1.0E-130
	VelocityZ                absolute 1.0E-130
	ForceX                   absolute 1.0E-130
	ForceY                   absolute 1.0E-130
	ForceZ                   absolute 1.0E-130
	Contact_ForceX           absolute 1.0E-130
	Contact_ForceY           absolute 1.0E-130
	Contact_ForceZ           absolute 1.0E-130
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume          absolute 1.0E-120
	Dilatation               absolute 1.0E-120
	Damage                   absolute 1.0E-120
	Number_Of_Neighbors      absolute 1.0E-120
