DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX   absolute 5.0E-14
	DisplacementY   absolute 5.0E-14
	DisplacementZ   absolute 5.0E-14
	VelocityX       absolute 1.0E-8
	VelocityY       absolute 1.0E-8
	VelocityZ       absolute 1.0E-8
	Force_DensityX  absolute 5.0
	Force_DensityY  absolute 5.0
	Force_DensityZ  absolute 5.0
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume absolute 1.0E-15
	Dilatation      absolute 5.0E-13
