#!/bin/bash
# Sample simulator to Dakota system call script

# $argv[1] is params.in FROM Dakota
# $argv[2] is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing peridigm.xml

dprepro $1 peridigm.template.xml peridigm.xml

# --------
# ANALYSIS
# --------

Peridigm peridigm.xml

# ---------------
# POST-PROCESSING
# ---------------

# extract force-density values in x-direction from the simulation output
grep -A 1 -i "Force_Density" peridigm_t1_0.vtu | tail -n 1 | sed 's/^[ \t]*//' | cut -d" " -f1,4 > results.tmp
force1="$(cat results.tmp | cut -d" " -f1)"
force2="$(cat results.tmp | cut -d" " -f2)"
data1=11700000.0
data2=-11700000.0
r1=$(echo $force1+$data1 | bc)
r2=$(echo $force2+$data2 | bc)
echo $r1 > results.tmp
echo $r2 >> results.tmp
mv results.tmp $2
