#!/bin/bash
# Sample simulator to Dakota system call script

# $argv[1] is params.in FROM Dakota
# $argv[2] is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing peridigm.xml

dprepro $1 peridigm.template.xml peridigm.xml

# --------
# ANALYSIS
# --------

Peridigm peridigm.xml

# ---------------
# POST-PROCESSING
# ---------------

# extract force-density values in x-direction from the simulation output
./ExtractNodalForces.py $2
