#!/bin/bash
# Sample simulator to Dakota system call script

# $argv[1] is params.in FROM Dakota
# $argv[2] is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing peridigm.xml

dprepro $1 peridigm.template.xml peridigm.xml

# --------
# ANALYSIS
# --------

Peridigm peridigm.xml

# ---------------
# POST-PROCESSING
# ---------------

# extract force-density values in x-direction from the simulation output
./exotxt peridigm.e out.txt
head -70 out.txt | tail -1 | cut -c19-35 > force1.tmp
head -72 out.txt | tail -1 | cut -c19-35 > force2.tmp
force1="$(cat force1.tmp)"
force2="$(cat force2.tmp)"
# bc doesn't like the + in scientific notation (i.e., 1.17000E+07), so remove it
floatVar1=$(echo $force1 | sed 's/\([0-9]*\(\.[0-9]*\)\?\)[eE]+\?\(-\?[0-9]*\)/(\1*10^\3)/g;s/^/scale=30;/'| bc)
floatVar2=$(echo $force2 | sed 's/\([0-9]*\(\.[0-9]*\)\?\)[eE]+\?\(-\?[0-9]*\)/(\1*10^\3)/g;s/^/scale=30;/'| bc)
data1=11700000.0
data2=-11700000.0
r1=$(echo $floatVar1+$data1 | bc)
r2=$(echo $floatVar2+$data2 | bc)
echo $r1 > results.tmp
echo $r2 >> results.tmp
mv results.tmp $2
