
#  *****************************************************************
#             EXODIFF	(Version: 3.02) Modified: 2020-05-06
#             Authors:  Richard Drake, rrdrake@sandia.gov           
#                       Greg Sjaardema, gdsjaar@sandia.gov          
#             Run on    2021/12/15   18:42:30 CET
#  *****************************************************************

#  FILE 1: /home/jritter/Projects/build/peridigm/test/verification/ShellBondFilter/QuadBondFilter/np1/QuadBondFilter.e
#   Title: Peridigm
#          Dim = 3, Blocks = 1, Nodes = 1000, Elements = 1000, Nodesets = 2, Sidesets = 0
#          Vars: Global = 0, Nodal = 3, Element = 1, Nodeset = 0, Sideset = 0, Times = 10


# ==============================================================
#  NOTE: All node and element ids are reported as global ids.

# NOTES:  - The min/max values are reporting the min/max in absolute value.
#         - Time values (t) are 1-offset time step numbers.
#         - Element block numbers are the block ids.
#         - Node(n) and element(e) numbers are 1-offset.

COORDINATES absolute 1.e-6    # min separation not calculated

TIME STEPS relative 1.e-6 floor 0.0     # min:               0 @ t1 max:           0.009 @ t10

# No GLOBAL VARIABLES

NODAL VARIABLES relative 1.e-6 floor 0.0
	DisplacementX  # min:               0 @ t1,n1	max:      0.10370005 @ t10,n491
	DisplacementY  # min:               0 @ t1,n1	max:      0.10370005 @ t10,n941
	DisplacementZ  # min:               0 @ t1,n1	max:      0.10370005 @ t10,n996

ELEMENT VARIABLES relative 1.e-6 floor 0.0
	Number_Of_Neighbors  # min:              28 @ t1,b1,e1	max:             122 @ t1,b1,e337

# No NODESET VARIABLES

# No SIDESET VARIABLES

