DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	Temperature_Change   absolute 1.0E-9
	Temperature          absolute 1.0E-9
	DisplacementX        absolute 1.0E-9
	DisplacementY        absolute 1.0E-9
	DisplacementZ        absolute 1.0E-9
	VelocityX            absolute 1.0E-9
	VelocityY            absolute 1.0E-9
	VelocityZ            absolute 1.0E-9
	ForceX               absolute 1.0E-2
	ForceY               absolute 1.0E-2
	ForceZ               absolute 1.0E-2
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume      absolute 1.0E-12
	Dilatation           absolute 1.0E-12
	Damage               absolute 1.0E-12
	Number_Of_Neighbors  absolute 1.0E-12
