DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX          absolute 1.0E-13
	DisplacementY          absolute 1.0E-13
	DisplacementZ          absolute 1.0E-13
	VelocityX              absolute 1.0E-13
	VelocityY              absolute 1.0E-13
	VelocityZ              absolute 1.0E-13
	Force_DensityX         absolute 1.0E-12
	Force_DensityY         absolute 1.0E-12
	Force_DensityZ         absolute 1.0E-12
ELEMENT VARIABLES absolute 1.E-12
	Weighted_Volume        absolute 1.0E-12
	Dilatation             absolute 1.0E-12
	Horizon                absolute 1.0E-12
	Number_Of_Neighbors    absolute 1.0E-12
