DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX   absolute 1.0E-9
	DisplacementY   absolute 1.0E-9
	DisplacementZ   absolute 1.0E-9
	VelocityX       absolute 5.0E-8
	VelocityY       absolute 5.0E-8
	VelocityZ       absolute 5.0E-8
	ForceX          absolute 10.0
	ForceY          absolute 10.0
	ForceZ          absolute 10.0
ELEMENT VARIABLES absolute 1.E-12
	Radius          absolute 1.0E-12
GLOBAL VARIABLES absolute 1.E-12
	Nonlinear_Solver_Iterations  absolute 1.0E-12

