DEFAULT TOLERANCE absolute 1.0E-9
COORDINATES absolute 1.0E-12
TIME STEPS absolute 1.0E-14
NODAL VARIABLES absolute 1.0E-12
	DisplacementX             absolute 1.0E-12
	DisplacementY             absolute 1.0E-12
	DisplacementZ             absolute 1.0E-12
	VelocityX                 absolute 1.0E-12
	VelocityY                 absolute 1.0E-12
	VelocityZ                 absolute 1.0E-12
	ForceX                    absolute 1.0E-12
	ForceY                    absolute 1.0E-12
	ForceZ                    absolute 1.0E-12
	Hourglass_Force_DensityX  absolute 1.0E-12
	Hourglass_Force_DensityY  absolute 1.0E-12
	Hourglass_Force_DensityZ  absolute 1.0E-12
ELEMENT VARIABLES absolute 1.E-12
	Volume                    absolute 1.0E-12
	Deformation_GradientXX    absolute 1.0E-12
	Deformation_GradientXY    absolute 1.0E-12
	Deformation_GradientXZ    absolute 1.0E-12
	Deformation_GradientYX    absolute 1.0E-12
	Deformation_GradientYY    absolute 1.0E-12
	Deformation_GradientYZ    absolute 1.0E-12
	Deformation_GradientZX    absolute 1.0E-12
	Deformation_GradientZY    absolute 1.0E-12
	Deformation_GradientZZ    absolute 1.0E-12
	Cauchy_StressXX           absolute 1.0E-12
	Cauchy_StressXY           absolute 1.0E-12
	Cauchy_StressXZ           absolute 1.0E-12
	Cauchy_StressYX           absolute 1.0E-12
	Cauchy_StressYY           absolute 1.0E-12
	Cauchy_StressYZ           absolute 1.0E-12
	Cauchy_StressZX           absolute 1.0E-12
	Cauchy_StressZY           absolute 1.0E-12
	Cauchy_StressZZ           absolute 1.0E-12
