name: Build and test docker image
on:
  push:
  pull_request:
  repository_dispatch:
    types: [trigger]

jobs:
  # Label of the container job
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and test Peridigm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile-test
          push: true
          tags: peridigm/peridigm:test
      - name: Minify docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile-master
          push: true
          tags: peridigm/peridigm:latest
